version: 2

jobs:
  jest:
    docker:
      - image: circleci/node:lts-jessie
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run: npm i --verbose
      - run: sudo npm i -g codecov
      - save_cache:
          key: npm-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm test -- --coverage
      - run: codecov
      - store_artifacts:
          path: coverage
          prefix: coverage
  # build:
  #   docker:
  #     - image: circleci/node:lts-jessie
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - npm-{{ checksum "package.json" }}
  #     - run: npm i --verbose
  #     - save_cache:
  #         key: npm-{{ checksum "package.json" }}
  #         paths:
  #           - ~/.npm
  #           - ~/.cache
  #     - run: npm run build
  #     - store_artifacts:
  #         path: build
  #         prefix: build
  cypress/run:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
            - npm-graphql-{{ checksum "node-explorer/package.json" }}
            - npm-cypress-{{ checksum "cypress/package.json" }}
      - run: npm i --verbose
      - run: npm i -g serve
      - save_cache:
          key: npm-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm run build
      - run: cd node-explorer; npm i --verbose;
      - save_cache:
          key: npm-cypress-{{ checksum "node-explorer/package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: cd node-explorer; npm run build;
      - run: cd node-explorer; DB_DIALECT=sqlite npm run sql db:migrate && npm run sql db:seed:all;
      - run: cd node-explorer; DB_DIALECT=sqlite ./build/app.js
      # - run: PORT=8080 npx serve -n
      - run: cd cypress && npm i --verbose
      - save_cache:
          key: npm-cypress-{{ checksum "cypress/package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      # - run: cd cypress && npx cypress run

workflows:
  version: 2
  test-only:
    jobs:
      - jest
      # - build
      - cypress/run
