version: 2

jobs:
  jest:
    docker:
      - image: circleci/node:lts-jessie
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run: npm i --verbose
      - run: sudo npm i -g codecov
      - save_cache:
          key: npm-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm test -- --coverage
      - run: codecov
      - store_artifacts:
          path: coverage
          prefix: coverage
  # build:
  #   docker:
  #     - image: circleci/node:lts-jessie
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - npm-{{ checksum "package.json" }}
  #     - run: npm i --verbose
  #     - save_cache:
  #         key: npm-{{ checksum "package.json" }}
  #         paths:
  #           - ~/.npm
  #           - ~/.cache
  #     - run: npm run build
  #     - store_artifacts:
  #         path: build
  #         prefix: build
  cypress/run:
    docker:
      - image: cypress/base:10
        environment:
          DB_DIALECT: sqlite
    steps:
      - checkout
      - run:
          name: pull graphql backend as GIT submodule
          command: |
            git submodule init
            git submodule update --remote
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}-{{ checksum "node-explorer/package.json" }}-{{ checksum "cypress/package.json" }}
      - run:
          name: fetch 'CWA' dependencies
          command: npm i --verbose
      - run:
          name: fetch 'SA' dependencies
          command: cd node-explorer && npm i --verbose
      - run:
          name: fetch 'serve' http server
          command: npm i -g serve
      - run:
          name: fetch 'cypress' dependencies
          command: cd cypress && npm i --verbose
      - save_cache:
          key: npm-{{ checksum "package.json" }}-{{ checksum "node-explorer/package.json" }}-{{ checksum "cypress/package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: assemble 'CWA' static assets
          command: npm run build
      - run:
          name: assemble 'SA' static assets && seed test database
          command: |
            cd node-explorer
            npm run build
            npm run sql db:migrate
            npm run sql db:seed:all
      # - run: PORT=8080 npx serve -n &
      # - run: cd node-explorer && PORT=8081 node ./build/app.js
      # - run: cd cypress && npx run cypress run

workflows:
  version: 2
  test-only:
    jobs:
      # - jest
      # - build
      - cypress/run
