version: 2.1
jobs:
  tests/functional:
    docker:
      - image: circleci/node:lts-jessie
    steps:
      - checkout
      - run: npm i --verbose
      - run: npm test -- --coverage --watchAll=false
      - run: sudo npm i -g codecov
      - run: codecov
      - store_artifacts:
          path: coverage
          prefix: coverage
  # - cypress:
  #   steps:
  #     - checkout
  #     - run: npm i --verbose
  #     - run: npm build
  #     - run: cd cypress; npm i --verbose
  #     - run: sudo npm i -g serve
  #     - run: serve -n
  # - cypress/run:
  #   steps:
  #     - run: cypress/node_modules/.bin/cypress run
workflows:
  version: 2
  test-only:
    jobs:
      - tests/functional
