version: 2

jobs:
  jest:
    docker:
      - image: circleci/node:lts-jessie
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run: npm i --verbose
      - run: sudo npm i -g codecov
      - save_cache:
          key: npm-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm test -- --coverage
      - run: codecov
      - store_artifacts:
          path: coverage
          prefix: coverage
  build:
    docker:
      - image: circleci/node:lts-jessie
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run: npm i --verbose
      - save_cache:
          key: npm-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm run build
      - store_artifacts:
          path: build
          prefix: build
    # cypress/install
    cypress/run:
        name: Chrome
        requires:
          - cypress/install
        # executor: cypress/browsers-chrome69
        # record: true
        # parallel: true
        # parallelism: 2
        # group: smoke tests
        # browser: chrome
        spec: cypress/specs/*
    # cypress/run:
    #   steps:
    #     - checkout
    #     - run: npm i --verbose
    #     - run: npm build
    #     # - run: cd cypress; npm i --verbose
    #     - run: sudo npm i -g serve
    #     - run: serve -n
#     cypress/install
#     # cypress/run:
#     #     name: 4 machines
#     #     requires:
#     #       - cypress/install
#     #     record: true
#     #     parallel: true
#     #     parallelism: 4
#     #     group: 4 machines
#     cypress/run:
#         name: Chrome
#         requires:
#           - cypress/install
#         # executor: cypress/browsers-chrome69
#         # record: true
#         # parallel: true
#         # parallelism: 2
#         # group: smoke tests
#         # browser: chrome
#         spec: cypress/specs/*
#     #   steps:
#     #     - run: cypress/node_modules/.bin/cypress run
workflows:
  version: 2
  test-only:
    jobs:
      - jest
      - build
      # - cypress/run
