version: '3'
services:
  cwa:
    container_name: cy-cwa
    build:
      context: .
      dockerfile: cypress.cwa.Dockerfile
    image: explorer-cwa-cypress
    ports:
      - 28080:28080
    environment:
      - PORT=28080
      - REACT_APP_API_PROTOCOL=http
      - REACT_APP_API_HOST=localhost
      - REACT_APP_API_PORT=28081
      - REACT_APP_WEBSITE_NAME=example
    entrypoint:
      - serve
    command: -n

  cypress:
    container_name: cy
    build:
      context: .
      dockerfile: cypress.Dockerfile
    image: cypress
    depends_on:
      - cwa
    environment:
      - CYPRESS_BASE_URL=http://cwa:28080
    entrypoint:
      - npm
    command: run test
    volumes:
      - ./cypress/specs:/www/specs
      - ./cypress/cypress.json:/www/cypress.json
